# Sample .travis.yml for R projects
language: r
sudo: false

r_github_packages:
     - etheleon/sigma

before_install:
      Rscript -e 'update.packages(ask = FALSE)'

warnings_are_errors: false

notifications:
  email:
    on_success: change
    on_failure: change
