language: R
cache: packages
sudo: false

r_github_packages:
  - etheleon/sigma

before_install:
  Rscript -e 'update.packages(ask = FALSE)'

before_deploy:
  - R -e "install.packages('roxygen2', repos = 'http://cran.rstudio.com')"
